### ISSUE TITLE
Seal of Vengeance

### ISSUE THREAD

**Issue by Xenatosa** [AznamirWoW/PallyPower#14]
Hello

the Seal of Vengeance, dont show up in Pallypower. I use German Client.
![Bild_2022-09-01_151948848](https://user-images.githubusercontent.com/12848200/187923868-2fd3ad7e-8ce6-468e-a042-bff63bdc820e.png)
![Bild_2022-09-01_152013216](https://user-images.githubusercontent.com/12848200/187923946-ff3c076c-6eb3-46ae-9c12-67901ab1e28d.png)
When i use Light it works.
![image](https://user-images.githubusercontent.com/12848200/187924040-d93211c2-9c90-4986-8578-6f244eabe457.png)

**Comment by Xenatosa** [comment]
I use Pallypower v1.4.8

**Comment by EsreverWoW** [comment]
This should be resolved in 1.4.9. It is being packaged and should be uploaded shortly. Apologies for the inconvenience.
