### ISSUE TITLE
1.14 Era - Not showing talented points in assignment pane

### ISSUE THREAD

**Issue by lvangh** [AznamirWoW/PallyPower#19]
As far as I can tell, things are working, except since the patch yesterday the assignment pane isn't detecting talented spells like 2/2 Wisdom. 
![image](https://github.com/AznamirWoW/PallyPower/assets/19690096/ea13ff5a-8456-4cc8-a403-adfcb6c9ecd7)

**Comment by AznamirWoW** [comment]
What does it show when you do
/dump GetTalentInfo(1, 10)
/dump GetTalentInfo(3, 1)
/dump GetTalentInfo(2, 12)

**Comment by lvangh** [comment]
![image](https://github.com/AznamirWoW/PallyPower/assets/19690096/708505db-9522-43e6-a10b-a47d33354a93)

**Comment by AznamirWoW** [comment]
here's a diff to try

diff --git "a/PallyPower.lua" "b/PallyPower.lua"
index 7db53c8..5c64e8c 100644
--- "a/PallyPower.lua"
+++ "b/PallyPower.lua"
@@ -1278,7 +1278,7 @@ function PallyPower:ScanSpells()
 						-- talent = talent + select(5, GetTalentInfo(1, 6)) -- Improved Blessing of Wisdom
 						talent = talent + select(5, GetTalentInfo(1, 6)) -- Improved Blessing of Wisdom
 					else
-						talent = talent + select(5, GetTalentInfo(1, 10)) -- Improved Blessing of Wisdom
+						talent = talent + select(5, GetTalentInfo(1, 6)) -- Improved Blessing of Wisdom
 					end
 				elseif i == 2 then
 					if self.isWrath then
@@ -1294,7 +1294,7 @@ function PallyPower:ScanSpells()
 					if self.isBCC then
 						talent = talent + select(5, GetTalentInfo(2, 14)) -- Blessing of Sanctuary
 					else
-						talent = talent + select(5, GetTalentInfo(2, 12)) -- Blessing of Sanctuary
+						talent = talent + select(5, GetTalentInfo(2, 9)) -- Blessing of Sanctuary
 					end
 				end
 				RankInfo[i].talent = talent
@@ -1319,7 +1319,7 @@ function PallyPower:ScanSpells()
 						-- talent = talent + select(5, GetTalentInfo(2, 11)) -- Improved Devotion Aura
 						talent = talent + select(5, GetTalentInfo(2, 2)) -- Improved Devotion Aura
 					else
-						talent = talent + select(5, GetTalentInfo(2, 1)) -- Improved Devotion Aura
+						talent = talent + select(5, GetTalentInfo(2, 2)) -- Improved Devotion Aura
 					end
 				elseif i == 2 then
 					if self.isWrath then
@@ -1327,7 +1327,7 @@ function PallyPower:ScanSpells()
 						-- talent = talent + select(5, GetTalentInfo(3, 14)) -- Sanctified Retribution
 						talent = talent + select(5, GetTalentInfo(3, 15)) -- Sanctified Retribution
 					else
-						talent = talent + select(5, GetTalentInfo(3, 11)) -- Improved Retribution Aura
+						talent = talent + select(5, GetTalentInfo(3, 4)) -- Improved Retribution Aura
 					end
 				elseif i == 3 then
 					if self.isWrath then
@@ -1337,13 +1337,13 @@ function PallyPower:ScanSpells()
 					elseif self.isBCC then
 						talent = talent + select(5, GetTalentInfo(2, 12)) -- Improved Concentration Aura
 					else
-						talent = talent + select(5, GetTalentInfo(2, 11)) -- Improved Concentration Aura
+						talent = talent + select(5, GetTalentInfo(2, 13)) -- Improved Concentration Aura
 					end
 				elseif i == 7 and not self.isWrath then
 					if self.isBCC then
 						talent = talent + select(5, GetTalentInfo(3, 14)) -- Sanctity Aura
 					else
-						talent = talent + select(5, GetTalentInfo(3, 13)) -- Sanctity Aura
+						talent = talent + select(5, GetTalentInfo(3, 6)) -- Sanctity Aura
 					end
 				end
 				AllPallys[self.player].AuraInfo[i].talent = talent

**Comment by AznamirWoW** [comment]
Need to update talent IDs in PallyPower,lua ScanSpells function

line 1281:  talent = talent + select(5, GetTalentInfo(1, 6)) -- Improved Blessing of Wisdom
line 1297:  talent = talent + select(5, GetTalentInfo(2, 9)) -- Blessing of Sanctuary
line 1322:  talent = talent + select(5, GetTalentInfo(2, 2)) -- Improved Devotion Aura
line 1330:  talent = talent + select(5, GetTalentInfo(3, 4)) -- Improved Retribution Aura
line 1340:  talent = talent + select(5, GetTalentInfo(2, 13)) -- Improved Concentration Aura
line 1346:  talent = talent + select(5, GetTalentInfo(3, 6)) -- Sanctity Aura

**Comment by AznamirWoW** [comment]
made a better(?) fix in v1.5.3-classic-alpha2
