### ISSUE TITLE
Remove paladin that left the party/raid from pallypower

### ISSUE THREAD

**Issue by Slivo-fr** [AznamirWoW/PallyPower#4]
Hi!

A the moment, when a paladin leave the group, PallyPower doesn't removes it from the UI, event with the "update" button (not sure about the name in english) and one needs to /reload to actually cleanup the pal list.

Would be great if pallypower could automatically remove them when they leave, or at least update the list when using the update button from the blessing assignment window

**Comment by SaschaJankowiak** [comment]
@AznamirWoW did a fix for given issue and tested with my guild in the last raids. @EsreverWoW found a missing Cooldown (LoH, Rank5) for the Wrath part and added this beforehand.
