### ISSUE TITLE
Add support for WowUp

### ISSUE THREAD

**Issue by jimsimon** [AznamirWoW/PallyPower#6]
CurseForge/Overwolf has blocked WowUp from accessing files hosted on its server. Please consider also publishing to WoWInterface or WowUpHub: https://wowup.io/guide/wowup/hub

**Comment by Treeston** [comment]
We publish as GitHub releases -- does WowUp not support this?

**Comment by AznamirWoW** [comment]
WowUp supports Github, all you need to do is use "Install from URL" option

**Comment by jodysaliba** [comment]
I've pulled the repo from WowUp. Seems like there isn't a separate zip for BCC vs Classic. Is the one zip compatible with both game versions?

**Comment by AznamirWoW** [comment]
> I've pulled the repo from WowUp. Seems like there isn't a separate zip for BCC vs Classic. Is the one zip compatible with both game versions?

The single .zip file contains the addon with multiple .toc files, WoW client automatically picks _Vanilla.toc for classic and defaults to PallyPower.toc for TBC

There are minor differences in the addon functionality between version and the single PallyPower.lua handles both.
