### ISSUE TITLE
Pets randomly assigned to different classes

### ISSUE THREAD

**Issue by Lesani** [AznamirWoW/PallyPower#8]
Sometimes pets are assigned to a class, and the icons for that class shows blue/yellow as if buffs are missing, even though buffs are not missing on any player character. "show pets" is checked, Version 1.44
Opening buff assignments then shows the pets under that class as if they were a player

also warlock pets are shown, even though you can't buff them

**Comment by Treeston** [comment]
Is this happening in combat or out of combat? There's a known issue with players being moved around in combat that I haven't gotten around to finding a good fix for.

**Comment by Lesani** [comment]
Regarding in combat I will observe next raid (thursday) specifically, Definitelly out of combat.

**Comment by SaschaJankowiak** [comment]
never experienced the described issue, is this still in observation?
